# Draft Configuration file for the DDPG agent and environment
min_servo_angle_rad: -0.7853
max_servo_angle_rad: 0.7853 

qnetwork:
  actor_hidden_layers: [300, 200, 100]  
  critic_hidden_layers: [300, 200, 100] 


agent:
  buffer_size: 10000  # Maximum size of the replay buffer
  batch_size: 32      # Number of experiences sampled from replay buffer for training
  gamma: 0.995         # Discount factor for future rewards
  learning_rate: 0.00001  # Learning rate for the optimizer
  optimizer: "delta_bar_delta"  # specify optimizer type
  dbd_increase_factor: 0.00001  # kappa: how much to increase learning rate
  dbd_decrease_factor: 0.0005   # phi: how much to decrease learning rate
  dbd_momentum: 0.0005          # alpha: momentum factor
  tau: 0.5           # Soft update factor for target network
  epsilon_initial: 1.0  # Initial exploration rate for epsilon-greedy policy
  epsilon_decay: 0.991   # Rate at which epsilon decays per episode
  epsilon_min: 0.01     # Minimum value for epsilon

environment:
  error_size: 6       # Size of the error vector
  state_size: 0       # Size of the state vector
  setpoint_size: 0    # Size of the setpoint vector
  servo_joints_size: 2      # Number of servo joints
  thruster_size: 4     # Number of thrusters was 4
  action_size: 4       # Number of discrete actions available
  max_episode_duration: 0.005  # Maximum duration (seconds) for each episode
  sampling_time: 0.25  # Sampling time (seconds) between actions was 0.208
  # action_interval: 2.0  # Interval (seconds) between consecutive actions
  thruster_history_length: 3  # Number of thruster actions stored for smoothness penalty
  servo_history_length: 5     # Number of servo states stored for smoothness penalty


reward_function:
  w1: 1.0             # Weight for performance error
  w2: 0.0             # Weight for servo smoothness penalty
  w3: 0.0              # Weight for thruster usage penalty (keep zero)
  w4: 0.0              # Weight for thruster smoothness penalty
  w5: 0.0              # Weight for servo angle penalty (keep zero)
  w6: 0.0              # Weight for thruster delta reward
  w7: 0.0              # Weight for action delta reward
  w8: 0.0               # Direction change penalty

#                       # x   y   z   surge sway heave roll pitch yaw angular vel
# state_error_weights: [0.0, 0.0, 0.1, 4.0, 3.0, 0.0, 3.0, 3.0, 0.25, 0.0, 0.0, 0.0]  # Weights for individual state errors

  state_error_weights: [
      # 0.0,  # x
      # 0.0,  # y
      1.0,  # z
      0.0,  # surge
      0.0,  # sway
      # 0.0,  # heave
      8.0,  # roll
      8.0,  # pitch
      1.0  # yaw
      # 0.0,  # angular_vel_x
      # 0.0,  # angular_vel_y
      # 0.0   # angular_vel_z
    ]

training:
  max_episodes: 10000    # Maximum episodes for training
  max_t: 10        # Maximum time per episode in secs
  target_avg_reward: 20  # Target average reward for early stopping
  plot_interval: 2    # Interval for updating plots during training
  random_seed: 42      # Random seed for reproducibility
  publish_interval: 10 # 10 secs if controller frq is 5Hz  

evaluation: 
  num_episodes: 10     # Number of episodes for evaluation

plotting:
  interactive: true    # Enable interactive plotting

others:
  random_seed: 42      # General random seed for reproducibility

